# Generated by Django 4.2.8 on 2023-12-15 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
    ]
