# Generated by Django 4.2.8 on 2023-12-16 02:39

import apps.primo.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primo', '0002_delete_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='url',
            field=models.URLField(validators=[apps.primo.validators.validate_prime_video_url]),
        ),
    ]
