# Generated by Django 4.2.8 on 2023-12-16 02:47
from django.core.management import call_command
from django.db import migrations


def load_fixture(apps, schema_editor):
    call_command(
        'loaddata', 'apps/primo/fixtures/categorys.json', app_label='primo'
    )
    call_command(
        'loaddata', 'apps/primo/fixtures/users.json', app_label='primo'
    )


class Migration(migrations.Migration):
    dependencies = [
        ('primo', '0003_alter_movie_url'),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
