version: '3'
services:
    python:
      container_name: prino_django
      build: ./.docker/python
      volumes:
         - ./:/usr/src/app
      restart: unless-stopped
      ports:
         - 9000:9000
      tty: true
      stdin_open: true
      command: sleep infinity
volumes:
    prino_db_data:
      driver: local